spring.application.name=email-mqtt-client-service

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ApplicationName=email-mqtt-client-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#logging.level.org.postgresql=DEBUG

spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB

eureka.client.service-url.defaultZone=http://${EUREKA_ADDRESS}:${EUREKA_PORT}/eureka/
eureka.client.service-url.instance.prefer-ip-address=true                # Register using IP instead of hostname
eureka.client.service-url.ip-address=${spring.cloud.client.ip-address}  # Auto-detects service IP
eureka.client.service-url.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.metadata-map.management.port=${management.server.port:${server.port}}


spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_POST}
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoint.prometheus.access=unrestricted