spring.application.name=email-mqtt-client-service

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ApplicationName=email-mqtt-client-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#logging.level.org.postgresql=DEBUG

spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_USERNAME}

#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false

# Eureka settings
eureka.client.service-url.defaultZone=http://${EUREKA_ADDRESS}:${EUREKA_PORT}/eureka/
eureka.client.service-url.instance.prefer-ip-address=true                # Register using IP instead of hostname
eureka.client.service-url.ip-address=${spring.cloud.client.ip-address}  # Auto-detects service IP
eureka.client.service-url.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.metadata-map.management.port=${management.server.port:${server.port}}


spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoint.prometheus.access=unrestricted

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.leak-detection-threshold=20000

logging.level.org.springframework.cloud.gateway=DEBUG
logging.file.name=${WIN_LOCATION}/logs/portal-onboard.log

logging.logback.rollingpolicy=max-file-size=20MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.file-name-pattern=${WIN_LOCATION}/logs/portal-onboard.%d{yyyy-MM-dd}.%i.log
