spring.application.name=email-mqtt-client-service

management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoint.prometheus.access=unrestricted



# Properties
success.code = 000
token.code = 001
reg.code = 010
payload.code = 011
block.code = 012
update.code = 020
del.code = 030
get.code = 040
exist.code = 050
notfound.code = 060
token.notfound.code = 061
role.code = 070
role.del.code = 080
role.update.code = 090

# Descriptions
payload.desc = Bad Request
success.desc = Successful
token.desc = Authentication Successful
token.notfound.desc = Authorization Token Not Found
reg.desc = Registered Successfully
notfound.desc = Not Found
update.desc = Updated Successfully
del.desc = Deleted Successfully
get.desc = Fetched Successfully
exist.desc = Already Exist

block.fail.desc = Blocked Unsuccessfully
reg.fail.desc = Registration Unsuccessfully
update.fail.desc = Update Unsuccessfully
del.fail.desc = Deletion Unsuccessfully
get.fail.desc = Fetching Unsuccessfully
