spring.application.name=email-mqtt-client-service

spring.datasource.url=jdbc:postgresql://172.16.10.28:8324/smarte-DB?ApplicationName=email-mqtt-client-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB

# Eureka server
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/

# Register using IP
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Optional
eureka.instance.hostname=localhost

# Management port
eureka.instance.metadata-map.management.port=${management.server.port:${server.port}}
#
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=memmcolapp@gmail.com
spring.mail.password=qwsjlktuzedkuddm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

